name: module-generator-pr

on:
  pull_request:
    paths:
      - '.support/module-generator/**'

concurrency:
  group: module-generator-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detekt_module-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true
          validate-wrappers: true

      - name: Run detekt and lint
        run: ./gradlew -p .support/module-generator detektMain -Pkotlin.incremental=false

  ktlint_module-generator:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run ktlint
        run: ./format --no-format --check-module-generator

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx16g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"
