name: Check

on:
  pull_request

jobs:
  danger:
    permissions:
      contents: read
      issues: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Danger
        uses: danger/kotlin@1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  assemble:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true
          validate-wrappers: true

      - name: Run assemble task
        run: ./gradlew assemble --no-configuration-cache -x jsBrowserDistribution -x wasmJsBrowserDistribution -x assembleRelease

  dependency_analysis:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true
          validate-wrappers: true

      - name: Run dependency analysis check
        run: ./gradlew buildHealth

  detekt:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true
          validate-wrappers: true

      - name: Run detekt
        run: ./gradlew detektAll

  build-ios-app:
    # Re-enable when https://github.com/JetBrains/compose-multiplatform/issues/4777 is resolved
    if: false
    permissions:
      contents: read
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true
          validate-wrappers: true

      - name: Build the ios app
        run: xcodebuild -project apps/ios/iosApp.xcodeproj -scheme iosApp -sdk iphonesimulator -configuration Debug build

  detekt-apple:
    # Re-enable when https://github.com/JetBrains/compose-multiplatform/issues/4777 is resolved
    if: false
    permissions:
      contents: read
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true
          validate-wrappers: true

      - name: Run detekt for apple targets
        run: ./gradlew detektAppleMain detektAppleTest

  ktlint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ktlint
        run: ./format --no-format

  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true
          validate-wrappers: true

      - name: Run Android lint
        run: ./gradlew :apps:android:lintRelease

  test:
    if: false
    permissions:
      contents: read
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .ci-java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          gradle-home-cache-cleanup: true
          validate-wrappers: true

      - name: Run tests
        run: ./gradlew allTests

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx16g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"
